### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by mikeliuvia** [GBert/openwrt-misc#1]
hello GBert:
               I see this i2s driver is for ar934x,and i want to know if this misc driver can be compatible with ar9331 i2s driver?

**Comment by GBert** [comment]
I don't know if this is working. If you need a I2S driver for ar9331 please have a look
http://8devices.com/community/viewtopic.php?f=13&t=572&start=10

**Comment by mikeliuvia** [comment]
Hi,GBert:
           thanks for it,seems there is no final solution, but it is worth watching.

**Comment by JiapengLi** [comment]
hi GBert and mikeliuvia,
How is the AR9331 i2s now? Is there an available AR934x datasheet?

**Comment by GBert** [comment]
Hi Jiapeng Li

my intention is not to make a generic i2s module for ar934x. I like to use i2s to generate bitstreams for railroad DCC, PWM or WS281x LED for example. IMHO is the i2s flexible enough to do that.
The buffering and DMA capability should be enough to get good timing without glitches. Some kind of offloading realtime tasks …

I don't know about a leaked ar934x docu. As far as i know, ar933x and ar934x i2s are very similar, but the clock setup register are differing. 
The code here is a dirty hack and doesn't work yet. Don't know if this will ever work ...

**Comment by GBert** [comment]
There seems to be a leaked pdf for 9344:
http://8devices.com/community/viewtopic.php?f=13&t=572&start=20

**Comment by GBert** [comment]
na
