### ISSUE TITLE
using i2s(plus DMA)

### ISSUE THREAD

**Issue by Deoptim** [GBert/openwrt-misc#2]
Theoretically, are we can use i2s(plus DMA) interface as high speed SPI?
Anyway, what the maximum output frequency-specific PLL(pll_cfg_25MHz or pll_cfg_40MHz or Higher)/DIV(for example, we set DIV=1)/CHANNELS for i2s (in practice)?
for example for SPI-master, need DO(Left or Right channel), DI(Line IN or Microphone), SCLK (Left or Right channel) = its 2 or 4 CHANNELS?

**Comment by GBert** [comment]
IMO you can use the i2s as fast SPI leaving the existing hardware SPI untouched. That's my intention: using the i2s differently.
AFAIK the speed is high: 44.1khz stereo with 32bit for left and right (2 channels) - which means 2.8 MHz. And even above this. Input is also possible.
The base frequenz is 25Mhz but there is a Audio PLL which could generate much higher frequencies.
Sorry I can't recall the formula but I have made some tests and I reached >100MHz, but the stability is questionable.
I want to use it for generic bitstreaming like drive WS281x leds e.g.
You are welcome to play with it. Indead I have to less time to do all that things only by myself.

BTW: The WR841 V8.x router is the best platform to test. The AR9341 SoC uses an internal multiplexer and you can put I2S on any port. And the V8.x also has a JTAG and and there are four  easy reachable ports whitout any hardware modification.

**Comment by fastwave2004** [comment]
Hi GBert,
is it possible to let ath-i2s-qca  driver to support AR9331 ? Does ar934x has the same I2S controller with AR9331

**Comment by GBert** [comment]
AR9331 and AR9341 are very similar. Sorry, I don't know if it is working (even on the AR9341).
I just "fixed" the compiling issues but didn't tested it yet ...

**Comment by GBert** [comment]
na
