### ISSUE TITLE
AR9344 - GPIO interrupt polarity issue

### ISSUE THREAD

**Issue by MrBan** [GBert/openwrt-misc#3]
Hi GBert,

I'm using your code regarding ATH79 gpio interrupt system on an AR9344-based board. Connected to GPIO11 I have a chip that gives me time synchronization emitting a square signal with a period of 1 second. I would like to generate an interrupt on each cycle, so I configured GPIO interrupt as IRQ_TYPE_EDGE_RISING.
The problem I'm experimenting is that instead on one interrupt per cycle I get two interrupts each period. The delay between these two interrupts is exactly equal to the time that the square signal stays on the high level (see attached image). This lead me think that for some reason the interrupt is sensible to both the rising and the falling edge.
Have you ever experienced something like that?

![graph](https://cloud.githubusercontent.com/assets/7239570/4648181/3382da1e-5480-11e4-9501-37c161e4bd2a.png)

Gaetano.

**Comment by GBert** [comment]
the IRQ code is now part of the vanilla / OpenWRT kernel - please check it again
