### ISSUE TITLE
Use 728-MIPS-ath79-add-gpio-irq.patch

### ISSUE THREAD

**Issue by flxkrmr** [GBert/openwrt-misc#5]
This is more a question than an issue.
I've added your patch 728-MIPS-ath79-add-gpio-irq.patch to my openwrt build, to add gpio interrupts to the carambola 2 board (AR9331).
When I export a gpio pin through sysfs, there is no 'edge' file to setup interrupts. A few printks in gpiolib.c showed that it is missing the to_irq function of a gpio_chip struct. I guess I have to add this in the board specific machine file (arch/mips/ath79/mach-carambola2.c) but I can't figure out how.
Could you give me any advice, how to add the interrupt functions correctly to the kernel?
Best.

**Comment by colosimo** [comment]
Hi fixkrmr, I'm not sure that the patch you are including is the only one needed for gpio irqs. I can suggest you to compare your code with the one in the git repository we use for lininoIO kernel: 

https://github.com/linino/kernel_3.3.8

I think you need these commits:
2f38d9c mips ath79, implement to_irq for ar933x soc
f9543cc mips, ath79, implement gpios interrupts.

On our boards, gpio interrupts are working and we have no specific code into mach-\* board specific file.

**Comment by flxkrmr** [comment]
Thanks a lot! I figured out a similar solution without the machine file, but it created a few kernel panics so I keep looking through your code.
